{"id":"compute\/v1\/managedinstancelastattempt","type":"","title":"Google\\Cloud\\Compute\\V1\\ManagedInstanceLastAttempt","name":"ManagedInstanceLastAttempt","description":"<p>Generated from protobuf message <code>google.cloud.compute.v1.ManagedInstanceLastAttempt<\/code><\/p>\n<p>Extends <a href=\"https:\/\/github.com\/protocolbuffers\/protobuf-php\/tree\/v3.21.9\/src\/Google\/Protobuf\/Internal\/Message.php\" target=\"_blank\">Google\\Protobuf\\Internal\\Message<\/a><\/p>","examples":[],"resources":[],"methods":[{"id":"__construct","type":"constructor","name":"__construct","source":"Compute\/src\/V1\/ManagedInstanceLastAttempt.php#L34","description":"<p>Constructor.<\/p>","examples":[],"resources":[],"params":[{"name":"data","description":"<p>Optional. Data for populating the Message object.<\/p>","types":["<a href=\"http:\/\/php.net\/manual\/en\/language.types.array.php\" target=\"_blank\">array<\/a>"],"optional":false,"nullable":null},{"name":"data.errors\n","description":"<p>[Output Only] Encountered errors during the last attempt to create or delete the instance.<\/p>","types":["<a data-custom-type=\"cloud-compute\/main\/compute\/v1\/errors\">Google\\Cloud\\Compute\\V1\\Errors<\/a>"],"optional":null,"nullable":null}],"exceptions":[],"returns":[]},{"id":"getErrors","type":"instance","name":"getErrors","source":"Compute\/src\/V1\/ManagedInstanceLastAttempt.php#L45","description":"<p>[Output Only] Encountered errors during the last attempt to create or delete the instance.<\/p>\n<p>Generated from protobuf field <code>optional .google.cloud.compute.v1.Errors errors = 315977579;<\/code><\/p>","examples":[],"resources":[],"params":[],"exceptions":[],"returns":[{"types":["<a data-custom-type=\"cloud-compute\/main\/compute\/v1\/errors\">Google\\Cloud\\Compute\\V1\\Errors<\/a>","<a href=\"http:\/\/php.net\/manual\/en\/language.types.null.php\" target=\"_blank\">null<\/a>"],"description":""}]},{"id":"setErrors","type":"instance","name":"setErrors","source":"Compute\/src\/V1\/ManagedInstanceLastAttempt.php#L67","description":"<p>[Output Only] Encountered errors during the last attempt to create or delete the instance.<\/p>\n<p>Generated from protobuf field <code>optional .google.cloud.compute.v1.Errors errors = 315977579;<\/code><\/p>","examples":[],"resources":[],"params":[{"name":"var","description":"<p>[Output Only] Encountered errors during the last attempt to create or delete the instance.<\/p>\n","types":["<a data-custom-type=\"cloud-compute\/main\/compute\/v1\/errors\">Google\\Cloud\\Compute\\V1\\Errors<\/a>"],"optional":false,"nullable":null}],"exceptions":[],"returns":[{"types":["<a data-custom-type=\"cloud-compute\/main\/compute\/v1\/managedinstancelastattempt\">Google\\Cloud\\Compute\\V1\\ManagedInstanceLastAttempt<\/a>"],"description":""}]}]}